name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.x.x
        
    - name: Publish
      run: dotnet publish -c Release -p:AssemblyName=csv-package-list --property:PublishDir=out -r ${{ matrix.target }} -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained true 

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'csv-package-list-${{ matrix.target }}.zip'
        directory: ${{ github.workspace }}/src/out
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v5
      with:
          retention-days: 1
          path: ${{ github.workspace }}/src/out/csv-package-list-${{ matrix.target }}.zip
          name: artifacts-${{ matrix.target }}-${{ github.run_number }}
  
  release:
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
    - name: Download Artifacts 
      uses: actions/download-artifact@v5
      with:
          pattern: artifacts-*-${{ github.run_number }}
          path: ${{ github.workspace }}/artifacts
          merge-multiple: 'true'

    - name: Create Release
      uses: ncipollo/release-action@v1.20.0
      with:
        allowUpdates: true 
        generateReleaseNotes: true
        artifacts: ${{ github.workspace }}/artifacts/*.zip
        tag: 1.0.0.${{ github.run_number }}
        name: 1.0.0.${{ github.run_number }}
