# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x
        
    - name: Publish
      run: dotnet publish -c Release -p:AssemblyName=csv-package-list --property:PublishDir=out/${{ matrix.target }} -r ${{ matrix.target }} -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained true 

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
          retention-days: 2
          path: ${{ github.workspace }}/src/out/${{ matrix.target }}
          name: csv-package-list-${{ matrix.target }}

    - name: Create Release
      uses: ncipollo/release-action@v1.16.0
      with:
        allowUpdates: true 
        artifacts: "artifacts/*.zip"
        tag: ${{ github.run_number }}
